# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.Project'),
        ),
    ]
