# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_auto_20190313_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
