# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_auto_20190320_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('L', 'LABELING'), ('C', 'CHECKING'), ('R', 'RELABELING')], max_length=20),
        ),
    ]
