# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_auto_20190320_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='choice',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
