# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0011_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('Labeling', 'LABELING'), ('Checking', 'CHECKING'), ('Rechecking', 'RELABELING'), ('Finish', 'FINISH')], max_length=20),
        ),
    ]
