# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-11 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0012_auto_20190411_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member',
        ),
    ]
